services:
    django:
        build: .
        container_name: talent-matching-django
        depends_on:
            - redis
        env_file: .env
        environment:
            - NEO4J_URI=${NEO4J_URI:-bolt://host.docker.internal:7689}
            - REDIS_URL=redis://redis:6379 # Hapus /0 di akhir URL
            - ENVIRONMENT=development
        ports:
            - "8000:8000"
        volumes:
            - ./logs:/var/log/scraper
            - ./uploaded_files:/app/uploaded_files
        restart: always
        develop:
            watch:
                - action: sync
                  path: ./talent_matching_server
                  target: /app/talent_matching_server
                  ignore:
                      - "**/__pycache__/"
                      - "**/*.pyc"
                - action: sync
                  path: ./core
                  target: /app/core
                  ignore:
                      - "**/__pycache__/"
                      - "**/*.pyc"
                      - "**/migrations/"
                - action: sync
                  path: ./manage.py
                  target: /app/manage.py
                - action: sync
                  path: ./utils
                  target: /app/utils
                  ignore:
                      - "**/__pycache__/"
                      - "**/*.pyc"
                - action: rebuild
                  path: requirements.txt

    celery:
        build: .
        container_name: talent-matching-celery
        depends_on:
            - redis
            - django
        env_file: .env
        environment:
            - HOME=/tmp
            - NEO4J_BOLT_URL=${NEO4J_BOLT_URL:-bolt://host.docker.internal:7689}
            - REDIS_URL=redis://redis:6379 # Hapus /0 di akhir URL
            - ENVIRONMENT=development
        command: python -m watchdog.watchmedo auto-restart --recursive --pattern="*.py" -- celery -A talent_matching_server worker --loglevel=info
        shm_size: "1gb"
        volumes:
            - ./logs:/var/log/scraper
            - ./uploaded_files:/app/uploaded_files
        restart: always
        develop:
            watch:
                - action: sync
                  path: ./talent_matching_server
                  target: /app/talent_matching_server
                - action: sync
                  path: ./core
                  target: /app/core

    redis:
        image: redis:alpine
        container_name: talent-matching-redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
    uploaded_files:
        driver: local
    redis_data:
